# Beispielscript für GBDB::runScript() oder SrvP::runScript()
# Übergabe z. B. mit:
# GBDB::runScript("scripts/greenql/makeUser.gql", [
#   "name" => $name,
#   "username" => $username,
#   "email" => $email,
#   "password" => $password,
#   "uid" => $uid
# ]);

declare _name = param("name");
declare _username = param("username");
declare _email = param("email");
declare _password = param("password");
declare _uid = param("uid");

declare _status_base = "Aktiv";

SEED users WITH uid=_uid, name=_name, username=_username, email=_email, password=_password IN main;
GROW TABLE _uid (firma, status) IN main;
GROW BASE _status_base;

declare _status_base = "Inaktiv";
GROW BASE _status_base;
